service: fredagsboten

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:Scan'
      Resource:
        Fn::GetAtt:
          - fredagsboten
          - Arn
  deploymentBucket:
    blockPublicAccess: true

functions:
  fredagsboten:
    handler: fredagsboten
    environment:
      DYNAMO_TABLE_NAME: ${env:DYNAMO_TABLE_NAME}
      SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}
      RUN_AT_TIME: 08:00
      TARGET_TIMEZONE: Europe/Stockholm
    events:
      - schedule: cron(0 * ? * FRI *)

resources:
  Resources:
    fredagsboten:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:DYNAMO_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: image_url
            AttributeType: S
        KeySchema:
          - AttributeName: image_url
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
